baseURL = 'https://cpro-iiit.github.io/CPro-IIITH-M25/'
languageCode = 'en-us'
title = 'CPro Mon 25'
theme = 'hugo-book'
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
  [markup.highlight]
    style = 'monokailight'

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 1

[[menu.after]]
  name = "Github"
  url = "https://github.com/cpro-iiit/"
  weight = 10

[params]
  # Theme (light/dark/auto)
  BookTheme = 'light'

  # Table of contents visibility
  BookToC = true

  # Logo path (put logo in web/static/logo1.png)
  BookLogo = 'logo1.png'

  # Root section shown in sidebar
  BookSection = 'docs'

  # GitHub repo used for "Edit this page" and "Last modified"
  BookRepo = 'https://github.com/cpro-iiit/cpro-iiit.github.io'

  # Format for displaying dates
  BookDateFormat = 'January 2, 2006'

  # Enable search bar
  BookSearch = true

  # Enable comments (requires Disqus setup — leave as false if unused)
  BookComments = false

  # Required by Hugo Book theme
  Sass = "book.scss"
